// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComputeCoordinator.proto

// Protobuf Java Version: 3.25.1
package src;

public final class ComputeCoordinatorOuterClass {
  private ComputeCoordinatorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComputeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComputeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.FileInput file_input = 1;</code>
     * @return Whether the fileInput field is set.
     */
    boolean hasFileInput();
    /**
     * <code>.FileInput file_input = 1;</code>
     * @return The fileInput.
     */
    DataStorageAPIOuterClass.FileInput getFileInput();
    /**
     * <code>.FileInput file_input = 1;</code>
     */
    DataStorageAPIOuterClass.FileInputOrBuilder getFileInputOrBuilder();

    /**
     * <code>string delimiter = 2;</code>
     * @return The delimiter.
     */
    java.lang.String getDelimiter();
    /**
     * <code>string delimiter = 2;</code>
     * @return The bytes for delimiter.
     */
    com.google.protobuf.ByteString
        getDelimiterBytes();
  }
  /**
   * Protobuf type {@code ComputeRequest}
   */
  public static final class ComputeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComputeRequest)
      ComputeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComputeRequest.newBuilder() to construct.
    private ComputeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComputeRequest() {
      delimiter_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComputeRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ComputeCoordinatorOuterClass.internal_static_ComputeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ComputeCoordinatorOuterClass.internal_static_ComputeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ComputeCoordinatorOuterClass.ComputeRequest.class, ComputeCoordinatorOuterClass.ComputeRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FILE_INPUT_FIELD_NUMBER = 1;
    private DataStorageAPIOuterClass.FileInput fileInput_;
    /**
     * <code>.FileInput file_input = 1;</code>
     * @return Whether the fileInput field is set.
     */
    @java.lang.Override
    public boolean hasFileInput() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.FileInput file_input = 1;</code>
     * @return The fileInput.
     */
    @java.lang.Override
    public DataStorageAPIOuterClass.FileInput getFileInput() {
      return fileInput_ == null ? DataStorageAPIOuterClass.FileInput.getDefaultInstance() : fileInput_;
    }
    /**
     * <code>.FileInput file_input = 1;</code>
     */
    @java.lang.Override
    public DataStorageAPIOuterClass.FileInputOrBuilder getFileInputOrBuilder() {
      return fileInput_ == null ? DataStorageAPIOuterClass.FileInput.getDefaultInstance() : fileInput_;
    }

    public static final int DELIMITER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object delimiter_ = "";
    /**
     * <code>string delimiter = 2;</code>
     * @return The delimiter.
     */
    @java.lang.Override
    public java.lang.String getDelimiter() {
      java.lang.Object ref = delimiter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        delimiter_ = s;
        return s;
      }
    }
    /**
     * <code>string delimiter = 2;</code>
     * @return The bytes for delimiter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDelimiterBytes() {
      java.lang.Object ref = delimiter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delimiter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getFileInput());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(delimiter_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, delimiter_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFileInput());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(delimiter_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, delimiter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ComputeCoordinatorOuterClass.ComputeRequest)) {
        return super.equals(obj);
      }
      ComputeCoordinatorOuterClass.ComputeRequest other = (ComputeCoordinatorOuterClass.ComputeRequest) obj;

      if (hasFileInput() != other.hasFileInput()) return false;
      if (hasFileInput()) {
        if (!getFileInput()
            .equals(other.getFileInput())) return false;
      }
      if (!getDelimiter()
          .equals(other.getDelimiter())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFileInput()) {
        hash = (37 * hash) + FILE_INPUT_FIELD_NUMBER;
        hash = (53 * hash) + getFileInput().hashCode();
      }
      hash = (37 * hash) + DELIMITER_FIELD_NUMBER;
      hash = (53 * hash) + getDelimiter().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ComputeCoordinatorOuterClass.ComputeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ComputeCoordinatorOuterClass.ComputeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeCoordinatorOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ComputeCoordinatorOuterClass.ComputeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComputeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComputeRequest)
        ComputeCoordinatorOuterClass.ComputeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ComputeCoordinatorOuterClass.internal_static_ComputeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ComputeCoordinatorOuterClass.internal_static_ComputeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ComputeCoordinatorOuterClass.ComputeRequest.class, ComputeCoordinatorOuterClass.ComputeRequest.Builder.class);
      }

      // Construct using ComputeCoordinatorOuterClass.ComputeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFileInputFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileInput_ = null;
        if (fileInputBuilder_ != null) {
          fileInputBuilder_.dispose();
          fileInputBuilder_ = null;
        }
        delimiter_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ComputeCoordinatorOuterClass.internal_static_ComputeRequest_descriptor;
      }

      @java.lang.Override
      public ComputeCoordinatorOuterClass.ComputeRequest getDefaultInstanceForType() {
        return ComputeCoordinatorOuterClass.ComputeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ComputeCoordinatorOuterClass.ComputeRequest build() {
        ComputeCoordinatorOuterClass.ComputeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ComputeCoordinatorOuterClass.ComputeRequest buildPartial() {
        ComputeCoordinatorOuterClass.ComputeRequest result = new ComputeCoordinatorOuterClass.ComputeRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ComputeCoordinatorOuterClass.ComputeRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileInput_ = fileInputBuilder_ == null
              ? fileInput_
              : fileInputBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.delimiter_ = delimiter_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ComputeCoordinatorOuterClass.ComputeRequest) {
          return mergeFrom((ComputeCoordinatorOuterClass.ComputeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ComputeCoordinatorOuterClass.ComputeRequest other) {
        if (other == ComputeCoordinatorOuterClass.ComputeRequest.getDefaultInstance()) return this;
        if (other.hasFileInput()) {
          mergeFileInput(other.getFileInput());
        }
        if (!other.getDelimiter().isEmpty()) {
          delimiter_ = other.delimiter_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getFileInputFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                delimiter_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private DataStorageAPIOuterClass.FileInput fileInput_;
      private com.google.protobuf.SingleFieldBuilderV3<
          DataStorageAPIOuterClass.FileInput, DataStorageAPIOuterClass.FileInput.Builder, DataStorageAPIOuterClass.FileInputOrBuilder> fileInputBuilder_;
      /**
       * <code>.FileInput file_input = 1;</code>
       * @return Whether the fileInput field is set.
       */
      public boolean hasFileInput() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       * @return The fileInput.
       */
      public DataStorageAPIOuterClass.FileInput getFileInput() {
        if (fileInputBuilder_ == null) {
          return fileInput_ == null ? DataStorageAPIOuterClass.FileInput.getDefaultInstance() : fileInput_;
        } else {
          return fileInputBuilder_.getMessage();
        }
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       */
      public Builder setFileInput(DataStorageAPIOuterClass.FileInput value) {
        if (fileInputBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fileInput_ = value;
        } else {
          fileInputBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       */
      public Builder setFileInput(
          DataStorageAPIOuterClass.FileInput.Builder builderForValue) {
        if (fileInputBuilder_ == null) {
          fileInput_ = builderForValue.build();
        } else {
          fileInputBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       */
      public Builder mergeFileInput(DataStorageAPIOuterClass.FileInput value) {
        if (fileInputBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            fileInput_ != null &&
            fileInput_ != DataStorageAPIOuterClass.FileInput.getDefaultInstance()) {
            getFileInputBuilder().mergeFrom(value);
          } else {
            fileInput_ = value;
          }
        } else {
          fileInputBuilder_.mergeFrom(value);
        }
        if (fileInput_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       */
      public Builder clearFileInput() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileInput_ = null;
        if (fileInputBuilder_ != null) {
          fileInputBuilder_.dispose();
          fileInputBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       */
      public DataStorageAPIOuterClass.FileInput.Builder getFileInputBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFileInputFieldBuilder().getBuilder();
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       */
      public DataStorageAPIOuterClass.FileInputOrBuilder getFileInputOrBuilder() {
        if (fileInputBuilder_ != null) {
          return fileInputBuilder_.getMessageOrBuilder();
        } else {
          return fileInput_ == null ?
              DataStorageAPIOuterClass.FileInput.getDefaultInstance() : fileInput_;
        }
      }
      /**
       * <code>.FileInput file_input = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          DataStorageAPIOuterClass.FileInput, DataStorageAPIOuterClass.FileInput.Builder, DataStorageAPIOuterClass.FileInputOrBuilder> 
          getFileInputFieldBuilder() {
        if (fileInputBuilder_ == null) {
          fileInputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              DataStorageAPIOuterClass.FileInput, DataStorageAPIOuterClass.FileInput.Builder, DataStorageAPIOuterClass.FileInputOrBuilder>(
                  getFileInput(),
                  getParentForChildren(),
                  isClean());
          fileInput_ = null;
        }
        return fileInputBuilder_;
      }

      private java.lang.Object delimiter_ = "";
      /**
       * <code>string delimiter = 2;</code>
       * @return The delimiter.
       */
      public java.lang.String getDelimiter() {
        java.lang.Object ref = delimiter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          delimiter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string delimiter = 2;</code>
       * @return The bytes for delimiter.
       */
      public com.google.protobuf.ByteString
          getDelimiterBytes() {
        java.lang.Object ref = delimiter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          delimiter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string delimiter = 2;</code>
       * @param value The delimiter to set.
       * @return This builder for chaining.
       */
      public Builder setDelimiter(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        delimiter_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string delimiter = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDelimiter() {
        delimiter_ = getDefaultInstance().getDelimiter();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string delimiter = 2;</code>
       * @param value The bytes for delimiter to set.
       * @return This builder for chaining.
       */
      public Builder setDelimiterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        delimiter_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComputeRequest)
    }

    // @@protoc_insertion_point(class_scope:ComputeRequest)
    private static final ComputeCoordinatorOuterClass.ComputeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ComputeCoordinatorOuterClass.ComputeRequest();
    }

    public static ComputeCoordinatorOuterClass.ComputeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComputeRequest>
        PARSER = new com.google.protobuf.AbstractParser<ComputeRequest>() {
      @java.lang.Override
      public ComputeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComputeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComputeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ComputeCoordinatorOuterClass.ComputeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ComputingResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComputingResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.Result result = 1;</code>
     * @return The result.
     */
    DataStorageAPIOuterClass.Result getResult();
  }
  /**
   * Protobuf type {@code ComputingResult}
   */
  public static final class ComputingResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComputingResult)
      ComputingResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComputingResult.newBuilder() to construct.
    private ComputingResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComputingResult() {
      result_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComputingResult();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ComputeCoordinatorOuterClass.internal_static_ComputingResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ComputeCoordinatorOuterClass.internal_static_ComputingResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ComputeCoordinatorOuterClass.ComputingResult.class, ComputeCoordinatorOuterClass.ComputingResult.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_ = 0;
    /**
     * <code>.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.Result result = 1;</code>
     * @return The result.
     */
    @java.lang.Override public DataStorageAPIOuterClass.Result getResult() {
      DataStorageAPIOuterClass.Result result = DataStorageAPIOuterClass.Result.forNumber(result_);
      return result == null ? DataStorageAPIOuterClass.Result.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != DataStorageAPIOuterClass.Result.UNKNOWN.getNumber()) {
        output.writeEnum(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != DataStorageAPIOuterClass.Result.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ComputeCoordinatorOuterClass.ComputingResult)) {
        return super.equals(obj);
      }
      ComputeCoordinatorOuterClass.ComputingResult other = (ComputeCoordinatorOuterClass.ComputingResult) obj;

      if (result_ != other.result_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ComputeCoordinatorOuterClass.ComputingResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ComputeCoordinatorOuterClass.ComputingResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeCoordinatorOuterClass.ComputingResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ComputeCoordinatorOuterClass.ComputingResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComputingResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComputingResult)
        ComputeCoordinatorOuterClass.ComputingResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ComputeCoordinatorOuterClass.internal_static_ComputingResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ComputeCoordinatorOuterClass.internal_static_ComputingResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ComputeCoordinatorOuterClass.ComputingResult.class, ComputeCoordinatorOuterClass.ComputingResult.Builder.class);
      }

      // Construct using ComputeCoordinatorOuterClass.ComputingResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ComputeCoordinatorOuterClass.internal_static_ComputingResult_descriptor;
      }

      @java.lang.Override
      public ComputeCoordinatorOuterClass.ComputingResult getDefaultInstanceForType() {
        return ComputeCoordinatorOuterClass.ComputingResult.getDefaultInstance();
      }

      @java.lang.Override
      public ComputeCoordinatorOuterClass.ComputingResult build() {
        ComputeCoordinatorOuterClass.ComputingResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ComputeCoordinatorOuterClass.ComputingResult buildPartial() {
        ComputeCoordinatorOuterClass.ComputingResult result = new ComputeCoordinatorOuterClass.ComputingResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ComputeCoordinatorOuterClass.ComputingResult result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ComputeCoordinatorOuterClass.ComputingResult) {
          return mergeFrom((ComputeCoordinatorOuterClass.ComputingResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ComputeCoordinatorOuterClass.ComputingResult other) {
        if (other == ComputeCoordinatorOuterClass.ComputingResult.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                result_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int result_ = 0;
      /**
       * <code>.Result result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @java.lang.Override public int getResultValue() {
        return result_;
      }
      /**
       * <code>.Result result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Result result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public DataStorageAPIOuterClass.Result getResult() {
        DataStorageAPIOuterClass.Result result = DataStorageAPIOuterClass.Result.forNumber(result_);
        return result == null ? DataStorageAPIOuterClass.Result.UNRECOGNIZED : result;
      }
      /**
       * <code>.Result result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(DataStorageAPIOuterClass.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Result result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComputingResult)
    }

    // @@protoc_insertion_point(class_scope:ComputingResult)
    private static final ComputeCoordinatorOuterClass.ComputingResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ComputeCoordinatorOuterClass.ComputingResult();
    }

    public static ComputeCoordinatorOuterClass.ComputingResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComputingResult>
        PARSER = new com.google.protobuf.AbstractParser<ComputingResult>() {
      @java.lang.Override
      public ComputingResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComputingResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComputingResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ComputeCoordinatorOuterClass.ComputingResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComputeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComputeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComputingResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComputingResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ComputeCoordinator.proto\032\024DataStorageA" +
      "PI.proto\"C\n\016ComputeRequest\022\036\n\nfile_input" +
      "\030\001 \001(\0132\n.FileInput\022\021\n\tdelimiter\030\002 \001(\t\"*\n" +
      "\017ComputingResult\022\027\n\006result\030\001 \001(\0162\007.Resul" +
      "t2D\n\022ComputeCoordinator\022.\n\007Compute\022\017.Com" +
      "puteRequest\032\020.ComputingResult\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DataStorageAPIOuterClass.getDescriptor(),
        });
    internal_static_ComputeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ComputeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComputeRequest_descriptor,
        new java.lang.String[] { "FileInput", "Delimiter", });
    internal_static_ComputingResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ComputingResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComputingResult_descriptor,
        new java.lang.String[] { "Result", });
    DataStorageAPIOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
